### ISSUE TITLE
DomElementGetter is not passed props

### ISSUE THREAD

**Issue by thantos** [single-spa/single-spa-html#13]
The contract for domElementGetter is inconsistent between plugins.

React passes in props: https://github.com/single-spa/single-spa-react/blob/master/src/single-spa-react.js#L154

Html does not: https://github.com/single-spa/single-spa-html/blob/master/src/single-spa-html.js#L42

**Comment by internettrans** [comment]
Agreed that we could improve this. Are you interested in submitting a pull request implementing this?

**Comment by thantos** [comment]
Yeah. I can.
