### ISSUE TITLE
Have some jquery script in html,how to make them work after mount

### ISSUE THREAD

**Issue by shuyue426** [single-spa/single-spa-html#6]
Dear,

I have a static html page which has some jquery script like:
$('#Button').on('click', function(e) {});

How to make the script work after mount the single-spa-html app,

I can pass a bind event callback in h5 enviroment,but since it is a webview also used in native app,
so better can make it work without external binding.

Thanks,

**Comment by internettrans** [comment]
One option is to add a custom [`mount` lifecycle function](https://single-spa.js.org/docs/building-applications#mount):

```js
const htmlLifecycles = singleSpaHtml({...})

export const bootstrap = [
  htmlLifecycles.bootstrap
];

export const mount = [
  htmlLifecycles.mount,
  async function() {
    $('#Button').on('click', function(e) {});
  }
];

export const unmount = [
  htmlLifecycles.unmount
];
```

Closing because I think i've answered this, but feel free to reopen or comment further
